#!/bin/bash
#
# FPP Install Script for Tailscale Plugin
#

PLUGIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
LOG_FILE="/var/log/fpp-tailscale.log"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

log "=== Installing Tailscale Plugin ==="

# Create log file
touch "$LOG_FILE"
chmod 644 "$LOG_FILE"

# Check if already installed
if command -v tailscale &> /dev/null; then
    log "Tailscale already installed: $(tailscale version | head -n1)"
else
    log "Installing Tailscale..."

    if curl -fsSL https://tailscale.com/install.sh | sh; then
        log "Tailscale installed successfully"
    else
        log "ERROR: Failed to install Tailscale"
        exit 1
    fi
fi

# Create necessary directories
log "Creating directories..."
mkdir -p /var/lib/tailscale
mkdir -p /var/run/tailscale
chmod 755 /var/lib/tailscale /var/run/tailscale

# Create default config in FPP standard location
CONFIG_FILE="/home/fpp/media/config/plugin.fpp-tailscale"
if [ ! -f "$CONFIG_FILE" ]; then
    log "Creating default configuration at $CONFIG_FILE..."

    # Use /etc/hostname if available — $(hostname) returns container IDs in Docker
    if [ -f /etc/hostname ]; then
        SYSTEM_HOSTNAME=$(cat /etc/hostname | tr -d '[:space:]')
    else
        SYSTEM_HOSTNAME=$(hostname)
    fi

    # If it looks like a container ID (12+ hex chars, no hyphens), use a safe default
    if echo "$SYSTEM_HOSTNAME" | grep -qE '^[0-9a-f]{12,}$'; then
        log "Detected container-style hostname ($SYSTEM_HOSTNAME), defaulting to 'fpp-player'"
        SYSTEM_HOSTNAME="fpp-player"
    fi

    cat > "$CONFIG_FILE" << EOF
; Tailscale Plugin Configuration
; Generated by FPP install script
auto_connect = false
accept_routes = false
advertise_exit = false
hostname = ${SYSTEM_HOSTNAME}
EOF
    chmod 644 "$CONFIG_FILE"
    log "Default configuration created with hostname: ${SYSTEM_HOSTNAME}"
else
    log "Configuration file already exists, preserving settings"
fi

# Start tailscaled daemon
log "Starting tailscaled daemon..."

start_tailscaled_manually() {
    sudo tailscaled --state=/var/lib/tailscale/tailscaled.state \
        --socket=/var/run/tailscale/tailscaled.sock \
        > /dev/null 2>&1 &
    sleep 3
    if pgrep -x "tailscaled" > /dev/null; then
        log "✓ Tailscaled started manually"
        return 0
    else
        log "ERROR: Could not start tailscaled"
        return 1
    fi
}

# Check if systemd is actually running before trying systemctl
if pidof systemd > /dev/null 2>&1 || systemctl is-system-running > /dev/null 2>&1; then
    log "systemd detected, enabling tailscaled service..."
    # Run enable and start separately so pipe to tee doesn't mask exit codes
    sudo systemctl enable tailscaled >> "$LOG_FILE" 2>&1
    if sudo systemctl start tailscaled >> "$LOG_FILE" 2>&1; then
        sleep 2
        if systemctl is-active --quiet tailscaled 2>/dev/null || pgrep -x "tailscaled" > /dev/null; then
            log "✓ Tailscaled running via systemd"
        else
            log "systemd start failed, falling back to manual start..."
            start_tailscaled_manually || exit 1
        fi
    else
        log "systemctl start failed, falling back to manual start..."
        start_tailscaled_manually || exit 1
    fi
else
    log "systemd not available, starting tailscaled manually..."
    start_tailscaled_manually || exit 1
fi

log "=== Tailscale Plugin Installation Complete ==="
log "Navigate to Status/Control → Tailscale VPN to connect"

exit 0
